theme: jekyll-theme-cayman
title: Whole Tale Summer Internship 2018
tagline: "Santiago Nunez-Corrales"
description: Whole Tale Internship 2018 - Scientific Reproducibility with MaxEnt
github_username:  snunezcr
