name: Santiago Nunez-Corrales

description: Whole Tale Internship 2018 - scientific repliation with MaxEnt

footer-links:
  email: snunezcr@gmail.com
  linkedin: https://www.linkedin.com/in/snunez/

theme: jekyll-theme-minimal

gems:
  - jekyll-sitemap
